[client]
showSidebarNavigation = false          #Automatisch generierten Sidebar ausblenden

[theme]
base = "dark"
blueBackgroundColor = "#01f7f732"    #BadgeBlau mit Design vom Logo anpassen
blueTextColor = "#01F7F6"          